# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/azhukov/Documents/ComputerVision2/andrei_zhukov/Sheet03

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/azhukov/Documents/ComputerVision2/andrei_zhukov/Sheet03

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/azhukov/Documents/ComputerVision2/andrei_zhukov/Sheet03/CMakeFiles /home/azhukov/Documents/ComputerVision2/andrei_zhukov/Sheet03/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/azhukov/Documents/ComputerVision2/andrei_zhukov/Sheet03/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sheet02

# Build rule for target.
sheet02: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sheet02
.PHONY : sheet02

# fast build rule for target.
sheet02/fast:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/build
.PHONY : sheet02/fast

src/AdaBoost.o: src/AdaBoost.cc.o

.PHONY : src/AdaBoost.o

# target to build an object file
src/AdaBoost.cc.o:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/AdaBoost.cc.o
.PHONY : src/AdaBoost.cc.o

src/AdaBoost.i: src/AdaBoost.cc.i

.PHONY : src/AdaBoost.i

# target to preprocess a source file
src/AdaBoost.cc.i:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/AdaBoost.cc.i
.PHONY : src/AdaBoost.cc.i

src/AdaBoost.s: src/AdaBoost.cc.s

.PHONY : src/AdaBoost.s

# target to generate assembly for a file
src/AdaBoost.cc.s:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/AdaBoost.cc.s
.PHONY : src/AdaBoost.cc.s

src/WeakClassifier.o: src/WeakClassifier.cc.o

.PHONY : src/WeakClassifier.o

# target to build an object file
src/WeakClassifier.cc.o:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/WeakClassifier.cc.o
.PHONY : src/WeakClassifier.cc.o

src/WeakClassifier.i: src/WeakClassifier.cc.i

.PHONY : src/WeakClassifier.i

# target to preprocess a source file
src/WeakClassifier.cc.i:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/WeakClassifier.cc.i
.PHONY : src/WeakClassifier.cc.i

src/WeakClassifier.s: src/WeakClassifier.cc.s

.PHONY : src/WeakClassifier.s

# target to generate assembly for a file
src/WeakClassifier.cc.s:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/WeakClassifier.cc.s
.PHONY : src/WeakClassifier.cc.s

src/sheet03_faceDetector.o: src/sheet03_faceDetector.cc.o

.PHONY : src/sheet03_faceDetector.o

# target to build an object file
src/sheet03_faceDetector.cc.o:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/sheet03_faceDetector.cc.o
.PHONY : src/sheet03_faceDetector.cc.o

src/sheet03_faceDetector.i: src/sheet03_faceDetector.cc.i

.PHONY : src/sheet03_faceDetector.i

# target to preprocess a source file
src/sheet03_faceDetector.cc.i:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/sheet03_faceDetector.cc.i
.PHONY : src/sheet03_faceDetector.cc.i

src/sheet03_faceDetector.s: src/sheet03_faceDetector.cc.s

.PHONY : src/sheet03_faceDetector.s

# target to generate assembly for a file
src/sheet03_faceDetector.cc.s:
	$(MAKE) -f CMakeFiles/sheet02.dir/build.make CMakeFiles/sheet02.dir/src/sheet03_faceDetector.cc.s
.PHONY : src/sheet03_faceDetector.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sheet02"
	@echo "... src/AdaBoost.o"
	@echo "... src/AdaBoost.i"
	@echo "... src/AdaBoost.s"
	@echo "... src/WeakClassifier.o"
	@echo "... src/WeakClassifier.i"
	@echo "... src/WeakClassifier.s"
	@echo "... src/sheet03_faceDetector.o"
	@echo "... src/sheet03_faceDetector.i"
	@echo "... src/sheet03_faceDetector.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

